# Generated by Django 2.2.5 on 2022-03-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20220303_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RommType',
            new_name='RoomType',
        ),
    ]
