# Generated by Django 2.2.5 on 2022-04-10 23:41

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20220317_1723'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='amenity',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='facility',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='houserule',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='roomtype',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
    ]
