# Generated by Django 2.2.5 on 2022-04-10 23:41

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20220411_0640'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='conversation',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
    ]
