# Generated by Django 2.2.5 on 2022-03-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='check_out',
            new_name='value',
        ),
    ]
