# Generated by Django 2.2.5 on 2022-03-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220303_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rooms',
            new_name='room',
        ),
    ]
