# Generated by Django 2.2.5 on 2022-04-10 23:41

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220410_1455'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
    ]
